[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/v1/*"
  to = "https://ubp-backend-production.up.railway.app/api/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
